USE codeup_test_db;
CREATE TABLE IF NOT EXISTS albums(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
artist VARCHAR(50) NOT NULL,
name VARCHAR(50) NOT NULL,
release_date INT,
sales DOUBLE,
genre VARCHAR(50),
PRIMARY KEY(id)
);